import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Copy, Download, Check, Loader2, Sparkles, ArrowRight, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

interface OutputSectionProps {
  output: string;
  isLoading: boolean;
  originalResume: string;
}

const OutputSection = ({ output, isLoading, originalResume }: OutputSectionProps) => {
  const [copied, setCopied] = useState(false);
  const [showComparison, setShowComparison] = useState(false);
  const { toast } = useToast();

  const handleCopy = async () => {
    if (!output) return;
    await navigator.clipboard.writeText(output);
    setCopied(true);
    toast({
      title: "Copied!",
      description: "The improved resume has been copied to clipboard.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    if (!output) return;
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "improved-resume.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({
      title: "Downloaded!",
      description: "Your improved resume has been downloaded as TXT.",
    });
  };

  const handleDownloadPdf = () => {
    if (!output) return;
    
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    const lineHeight = 6;
    let yPosition = margin;

    // Add header with gradient-like styling
    pdf.setFillColor(139, 92, 246); // Purple color
    pdf.rect(0, 0, pageWidth, 15, "F");
    
    pdf.setTextColor(255, 255, 255);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(12);
    pdf.text("AI Resume Improver Pro", margin, 10);
    
    yPosition = 25;

    // Reset text color for content
    pdf.setTextColor(30, 30, 30);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    // Split text into lines that fit the page width
    const lines = pdf.splitTextToSize(output, maxWidth);

    lines.forEach((line: string) => {
      // Check if we need a new page
      if (yPosition + lineHeight > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }

      // Check if line is a section header (all caps or ends with colon)
      const isHeader = /^[A-Z\s]+:?$/.test(line.trim()) || 
                       (line.trim().endsWith(":") && line.trim().length < 50);
      
      if (isHeader && line.trim().length > 0) {
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(12);
        pdf.setTextColor(139, 92, 246); // Purple for headers
        yPosition += 3; // Add extra spacing before headers
      } else {
        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(11);
        pdf.setTextColor(30, 30, 30);
      }

      pdf.text(line, margin, yPosition);
      yPosition += lineHeight;
    });

    // Add footer
    const totalPages = pdf.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(9);
      pdf.setTextColor(150, 150, 150);
      pdf.text(
        `Page ${i} of ${totalPages} | Generated by AI Resume Improver Pro`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );
    }

    pdf.save("improved-resume.pdf");
    
    toast({
      title: "PDF Downloaded!",
      description: "Your improved resume has been downloaded as a professional PDF.",
    });
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="glass-card p-6 md:p-8"
    >
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-gradient-to-br from-green-600/20 to-teal-600/20">
            <Sparkles className="w-6 h-6 text-green-400" />
          </div>
          <div>
            <h2 className="text-xl font-bold">AI Output</h2>
            <p className="text-sm text-muted-foreground">Your enhanced resume content</p>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          {originalResume && output && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowComparison(!showComparison)}
              className="text-xs"
            >
              {showComparison ? "Hide" : "Show"} Comparison
            </Button>
          )}
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            disabled={!output || isLoading}
            className="text-xs"
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleDownloadTxt}
            disabled={!output || isLoading}
            className="text-xs"
            title="Download as TXT"
          >
            <Download className="w-4 h-4" />
          </Button>
          <Button
            variant="default"
            size="sm"
            onClick={handleDownloadPdf}
            disabled={!output || isLoading}
            className="text-xs gap-1"
            title="Download as PDF"
          >
            <FileText className="w-4 h-4" />
            PDF
          </Button>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {isLoading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center py-20"
          >
            <div className="relative">
              <div className="w-16 h-16 rounded-full border-4 border-primary/20" />
              <div className="absolute inset-0 w-16 h-16 rounded-full border-4 border-primary border-t-transparent animate-spin" />
            </div>
            <p className="mt-6 text-muted-foreground">AI is enhancing your resume...</p>
            <div className="flex gap-1 mt-4">
              {[0, 1, 2].map((i) => (
                <div
                  key={i}
                  className="w-2 h-2 rounded-full bg-primary animate-pulse"
                  style={{ animationDelay: `${i * 0.2}s` }}
                />
              ))}
            </div>
          </motion.div>
        ) : showComparison && originalResume && output ? (
          <motion.div
            key="comparison"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="grid md:grid-cols-2 gap-4"
          >
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm font-medium text-muted-foreground">
                <span className="w-2 h-2 rounded-full bg-orange-400" />
                Before
              </div>
              <div className="p-4 rounded-xl bg-muted/30 border border-border/50 min-h-[300px] max-h-[500px] overflow-y-auto">
                <pre className="whitespace-pre-wrap text-sm text-muted-foreground">{originalResume}</pre>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex items-center gap-2 text-sm font-medium text-green-400">
                <span className="w-2 h-2 rounded-full bg-green-400" />
                After
              </div>
              <div className="p-4 rounded-xl bg-green-600/5 border border-green-500/30 min-h-[300px] max-h-[500px] overflow-y-auto">
                <pre className="whitespace-pre-wrap text-sm text-foreground">{output}</pre>
              </div>
            </div>
          </motion.div>
        ) : output ? (
          <motion.div
            key="output"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="p-4 rounded-xl bg-muted/30 border border-border/50 min-h-[300px] max-h-[600px] overflow-y-auto"
          >
            <pre className="whitespace-pre-wrap text-sm leading-relaxed">{output}</pre>
          </motion.div>
        ) : (
          <motion.div
            key="empty"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="flex flex-col items-center justify-center py-20 text-center"
          >
            <div className="p-4 rounded-full bg-muted/50 mb-4">
              <ArrowRight className="w-8 h-8 text-muted-foreground" />
            </div>
            <p className="text-muted-foreground">
              Select a tool and click "Run Analysis" to see AI-enhanced results here
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};

export default OutputSection;
